import "./globals.css";

import { Righteous } from "@next/font/google";

const righteous = Righteous({
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={righteous.className}>{children}</body>
    </html>
  );
}
